import streamlit as st
import matplotlib.pyplot as plt
import pandas as pd

# ==================================================
# PAGE CONFIGURATION
# ==================================================

st.set_page_config(
    page_title="BuildQuote AI Reports",
    page_icon="📄",
    layout="wide"
)

st.title("📄 BuildQuote AI Reports")
st.caption("Professional Construction Cost Report")

# ==================================================
# CHECK SESSION
# ==================================================

if "estimate" not in st.session_state:
    st.warning("No project estimate found.")
    st.info("Go to **New Project** and generate an estimate first.")
    st.stop()

estimate = st.session_state["estimate"]
project = estimate["project"]

# ==================================================
# PROJECT DETAILS
# ==================================================

st.header("🏗 Project Information")

col1, col2 = st.columns(2)

with col1:
    st.write(f"**County:** {project['County']}")
    st.write(f"**Project Type:** {project['Project Type']}")
    st.write(f"**House Type:** {project['House Type']}")

with col2:
    st.write(f"**Wall Material:** {project['Block Type']}")
    st.write(f"**Roof Type:** {project['Roof Type']}")
    st.write(f"**Bedrooms:** {project['Bedrooms']}")

st.divider()

# ==================================================
# COST SUMMARY
# ==================================================

st.header("💰 Cost Summary")

summary = pd.DataFrame({
    "Item": [
        "Subtotal",
        "VAT (16%)",
        "Grand Total"
    ],
    "Amount (KES)": [
        estimate["subtotal"],
        estimate["vat"],
        estimate["grand_total"]
    ]
})

st.dataframe(summary, use_container_width=True)

st.divider()

# ==================================================
# COST CHART
# ==================================================

st.header("📊 Cost Distribution")

fig, ax = plt.subplots(figsize=(6,4))

ax.pie(
    [
        estimate["subtotal"],
        estimate["vat"]
    ],
    labels=["Construction Cost", "VAT"],
    autopct="%1.1f%%",
    startangle=90
)

ax.set_title("Project Cost Distribution")

st.pyplot(fig)

st.divider()

# ==================================================
# BILL OF QUANTITIES
# ==================================================

st.header("📋 Bill of Quantities")

boq_df = pd.DataFrame(estimate["boq"])

st.dataframe(
    boq_df,
    use_container_width=True
)

st.divider()

# ==================================================
# MATERIAL REPORT
# ==================================================

st.header("🧱 Material Report")

st.json(estimate["materials"])

st.divider()

# ==================================================
# LABOUR REPORT
# ==================================================

st.header("👷 Labour Report")

st.json(estimate["labour"])

st.divider()

# ==================================================
# SECTION TOTALS
# ==================================================

st.header("🏗 Construction Sections")

sections = [
    "foundation",
    "walling",
    "roof",
    "finishes",
    "electrical",
    "plumbing",
    "doors_windows"
]

rows = []

for section in sections:

    if section in estimate:

        rows.append({
            "Section": section.replace("_", " ").title(),
            "Subtotal": estimate[section]["subtotal"]
        })

section_df = pd.DataFrame(rows)

st.dataframe(
    section_df,
    use_container_width=True
)

if not section_df.empty:

    fig, ax = plt.subplots(figsize=(8,4))

    ax.bar(
        section_df["Section"],
        section_df["Subtotal"]
    )

    ax.set_ylabel("KES")
    ax.set_title("Cost by Construction Section")

    plt.xticks(rotation=25)

    st.pyplot(fig)

st.divider()

# ==================================================
# REPORT SUMMARY
# ==================================================

st.header("📝 Report Summary")

st.success(f"Estimated Project Cost: KES {estimate['grand_total']:,.2f}")

st.info(
    "This report summarizes the estimated construction costs, "
    "materials, labour, and Bill of Quantities generated by BuildQuote AI."
)

st.caption(
    "© 2026 BuildQuote AI | Professional Construction Estimation Platform"
)